### ISSUE TITLE
Syntax Highlighting not working on Large .pwn files... 

### ISSUE THREAD

**Issue by rajabilal555** [Larcenny/language-pawn#5]
Syntax Highlighting not working on Large .pwn files... 

I have a big script...
you might say almost `137077` lines and the Syntax highlighting is not working...
I tried and open a filter-script and it worked...

**Comment by renatogg** [comment]
The problem isn't in the syntax. Atom doesn't support files larger than 2mb. 1mb+ files don't have syntax highlighting because Atom disables it.
If you develop a gamemode in just 1 file, Atom isn't for you (Sublime / Notepad++ are better for large files). If you want to use Atom, make a modular gamemode.
